[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "venc"
authors = [{name = "Denis Salem", email = "denissalem@tuxfamily.org"}]
readme = "README.md"
license = {file = "LICENSE.md"}
classifiers = [
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Programming Language :: Python :: 3",
]
dynamic = ["version", "description"]
dependencies = [
"asciidoc3",
"docutils",
"latex2mathml",
"mistletoe",
"pygments",
"pyyaml",
"unidecode".
]

[project.urls]
Home = "https://venc.software"

[project.scripts]
venc = "venc.venc:main"

[tool.pylint.format]
max-line-length = 95
