author_description: 
author_email: 
author_name: Denis Salem
blog_description: Un générateur de site statique qui casse des briques. VenC est tellement rapide qu'il enfreint le principe de causalité et produit de l'énergie surunitaire !
blog_language: fr
blog_name: VenC
blog_url: https://denissalem.tuxfamily.org/VenC
code_highlight_css_override: false
date_format: '%A %d. %B %Y'
disable_archives: true
disable_atom_feed: true
disable_categories: true
disable_chapters: false
disable_main_thread: true
disable_rss_feed: true
disable_single_entries: true
entries_per_pages: 50
feed_length: 15
ftp_host: ftp.tuxfamily.org
ftp_port: 21
license: 'CC-By-SA'
markup_language: Markdown
parallel_processing: 1
paths:
  archives_directory_name: '%Y-%m'
  archives_sub_folders: ''
  atom_file_name: atom.xml
  categories_sub_folders: ''
  category_directory_name: '{category}'
  chapter_directory_name: '{chapter_name}'
  chapters_sub_folders: ''
  entries_sub_folders: 'DEBUG/{entry_title}/'
  entry_file_name: index.html
  ftp: venc/venc.software-web/htdocs/
  index_file_name: index{page_number}.html
  rss_file_name: rss.xml
path_encoding: ''
reverse_thread_order: true
server_port: 8888
sort_by: chapter
text_editor:
  - geany
  - -i
columns: 1
force_entry_content: true
tree_test:
    - a:
        - b:
            - c
            - d
        - e:
            - f
    - g
my_taxonomy:
  - Medium & Technique
  - Licence
