info:
    description : 'theme_description_academik'
    
override:
    columns: 1
    path:
        atom_file_name: 'atom_feed.xml'
        rss_file_name: 'rss_feed.xml'
        
assets_dependencies: ['feed-logo.png', 'VenC-Scripts-Bootstrap-0.0.0.js', 'VenC-Tree-0.1.0.js', 'VenC-Infinite-Scroll-1.2.0.js']
