info:
    description : 'theme_description_gentle'
    
override:
    columns: 1
    disable_chapters: true
    nsfw_image: 'VenC_nsfw.png'

assets_dependencies: ['VenC-Infinite-Scroll-1.1.0.js', 'VenC_nsfw.png', 'VenC_info_icon1.png', 'VenC_warning_icon1.png']
includes_dependencies: ['nsfw.html']
