#! /usr/bin/python3


import sys

from VenC.export import ExportBlog
from VenC.export import EditAndExport
from VenC.export import ExportAndRemoteCopy
from VenC.export import RemoteCopy
from VenC.helpers import Notify
from VenC.install import InstallTheme
from VenC.l10n import Messages; 
from VenC.new import NewBlog
from VenC.new import NewEntry
from VenC.print import PrintVersion
from VenC.print import PrintThemes
from VenC.print import PrintHelp


commandIndex = {"-v":                   [PrintVersion, 0],
                "-nb":                  [NewBlog, -1],
                "-ne":                  [NewEntry, 2],
                "-xb":                  [ExportBlog, 1],
                "-ex":                  [EditAndExport, 1],
                "-xftp":                [ExportAndRemoteCopy, 1],
                "-rc":                  [RemoteCopy, 0],
                "-it":                  [InstallTheme, 1],
                "-h":                   [PrintHelp, 0],
                "-t":                   [PrintThemes, 0],
                "--themes":             [PrintThemes, 0],
                "--help":               [PrintHelp, 0],
                "--remote-copy":        [RemoteCopy, 0],
                "--export-via-ftp":     [ExportAndRemoteCopy, 1],
                "--edit-and-export":    [EditAndExport, 1],
                "--install-theme":      [InstallTheme, 1],
                "--export-blog":        [ExportBlog, 1],
                "--new-entry":          [NewEntry, 2],
                "--new-blog":           [NewBlog, -1],
                "--version":            [PrintVersion, 0]}

def argv_handler(argv=None):
    argv = argv if argv != None else sys.argv[1:]
    if argv != []: 
       if argv[0] in commandIndex:
           if commandIndex[argv[0]][1] != -1: 
               arguments = argv[1:commandIndex[argv[0]][1]+1]
           
           else:
               arguments = list()
               for argument in argv[1:]:
                   if argument not in commandIndex.keys():
                       arguments.append(argument)

                   else:
                       break

           commandIndex[argv[0]][0](arguments)
           argv_handler(argv[len(arguments)+1:])

       else:
           Notify(Messages.unknownCommand.format(argv[0]),"RED")
           argv_handler(argv[1:])

if sys.argv[1:] != []: 
    argv_handler()

else:
    Notify(Messages.nothingToDo,"YELLOW")

